"use client";

import type { DashboardData } from "@/lib/contracts";
import { isOutbreakArtefact } from "@/lib/contracts";
import type { SectionId } from "../Sidebar";

const THRESHOLD = 0.75;

/**
 * The observation feed.
 *
 * An eval_score of 0 means "generated but never scored" — observations written
 * in-app by Fireworks have not been through Braintrust. That renders as
 * "unscored", never as a passing badge, because a green tick on an unchecked
 * claim is the exact failure the eval layer exists to prevent.
 */
export function Observations({
  data,
  onNavigate,
  onHighlight,
}: {
  data: DashboardData;
  onNavigate: (id: SectionId) => void;
  onHighlight: (clusterId: string) => void;
}) {
  const withObs = data.clusters.filter((c) => c.observation);
  const unscored = withObs.filter((c) => !c.observation!.eval_score).length;

  return (
    <div className="space-y-6">
      <div>
        <p className="eyebrow">Observations</p>
        <h2 className="display mt-1.5 text-2xl text-ink">
          Written from the cluster statistics
        </h2>
        <p className="mt-2 max-w-[62ch] text-sm leading-relaxed text-muted">
          Generated by Fireworks under a prompt that forbids inventing or
          calculating numbers. Where a Braintrust faithfulness score exists it is
          shown; where it does not, the card says unscored.
        </p>
      </div>

      {unscored > 0 && (
        <p className="border-l-2 border-amber bg-amber-tint px-3 py-2 text-xs leading-relaxed text-amber">
          <strong className="font-semibold">
            {unscored} of {withObs.length} observations are unscored.
          </strong>{" "}
          They were generated but never checked against the cluster data. Treat
          the wording as unverified.
        </p>
      )}

      {withObs.length === 0 ? (
        <div className="border border-hairline bg-card p-6">
          <p className="text-sm text-muted">
            No observations in this dataset. Load a source that includes
            observations.json, or generate them from the cluster summary on the
            source screen.
          </p>
        </div>
      ) : (
        <ul className="space-y-4">
          {withObs.map((c) => {
            const o = c.observation!;
            const scored = o.eval_score > 0;
            const grounded = scored && o.eval_score >= THRESHOLD;
            const artefact = isOutbreakArtefact(c.summary);
            return (
              <li key={c.cluster_id} className="border border-hairline bg-card p-5">
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div className="min-w-0">
                    <p className="eyebrow">
                      Cluster {c.cluster_id} · {c.summary.n_genes} genes
                    </p>
                    <h3 className="display mt-1.5 text-lg text-ink">
                      {o.headline}
                    </h3>
                  </div>
                  <span
                    className={`inline-flex shrink-0 items-baseline gap-1.5 border px-2 py-1 text-xs ${
                      !scored
                        ? "border-hairline bg-paper text-muted"
                        : grounded
                          ? "border-viridian/30 bg-viridian-tint text-viridian"
                          : "border-amber/40 bg-amber-tint text-amber"
                    }`}
                  >
                    <span className="eyebrow !text-inherit">
                      {!scored ? "unscored" : grounded ? "grounded" : "review"}
                    </span>
                    {scored && (
                      <span className="tabular font-medium">
                        {o.eval_score.toFixed(2)}
                      </span>
                    )}
                    <span className="text-[0.6875rem] opacity-70">
                      {o.confidence}
                    </span>
                  </span>
                </div>

                <p className="mt-3 max-w-[68ch] text-sm leading-relaxed text-ink/85">
                  {o.observation}
                </p>

                {artefact && (
                  <p className="mt-3 border-l-2 border-amber bg-amber-tint px-3 py-2 text-xs leading-relaxed text-amber">
                    This cluster sits in a single country or year. Read it as one
                    clonal or plasmid-linked event.
                  </p>
                )}

                <div className="mt-3 flex flex-wrap items-baseline gap-x-4 gap-y-1 text-xs text-muted">
                  <span>
                    <span className="tabular text-ink">{c.resistant}</span>{" "}
                    resistant,{" "}
                    <span className="tabular text-ink">{c.susceptible}</span>{" "}
                    susceptible of{" "}
                    <span className="tabular">{c.phenotyped}</span> phenotyped
                  </span>
                  <button
                    type="button"
                    onClick={() => {
                      onHighlight(c.cluster_id);
                      onNavigate("clusters");
                    }}
                    className="cursor-pointer border-b border-dashed border-muted pb-px text-violet hover:border-violet"
                  >
                    See the cluster
                  </button>
                </div>
              </li>
            );
          })}
        </ul>
      )}
    </div>
  );
}
