"use client";

import { ShieldCheck, AlertTriangle, Sparkles } from "lucide-react";
import { useMemo } from "react";
import { insights as fallbackInsights } from "@/lib/mock-data";
import { useWorkspace } from "@/lib/workspace-store";
import { deriveChartData } from "@/lib/data-sources";

// Next.js page
export default Insights;

function Insights() {
  const { dashboardData } = useWorkspace();
  const derived = useMemo(() => (dashboardData ? deriveChartData(dashboardData) : null), [dashboardData]);
  const list = derived?.insights ?? fallbackInsights.map((i) => ({ ...i, evalScore: i.grounded ? 0.92 : 0.72 }));

  return (
    <div className="p-6 lg:p-10 max-w-5xl mx-auto">
      <div className="text-xs uppercase tracking-wider text-teal font-semibold">AI Insights</div>
      <h1 className="mt-1 text-2xl lg:text-3xl font-bold tracking-tight text-foreground">
        Grounded insight feed
      </h1>
      <p className="mt-1 text-sm text-muted-foreground">
        Generated by Fireworks AI · validated by Braintrust.
      </p>

      <div className="mt-6 space-y-4">
        {list.map((i) => (
          <div key={i.id} className="card-elevated rounded-xl p-5">
            <div className="flex items-start gap-3">
              <div
                className={`mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${
                  i.grounded ? "bg-success/10 text-success" : "bg-accent text-accent-foreground"
                }`}
              >
                {i.grounded ? <ShieldCheck className="h-4 w-4" /> : <AlertTriangle className="h-4 w-4" />}
              </div>
              <div className="flex-1">
                <div className="flex items-center justify-between gap-2">
                  <div className="text-sm font-semibold text-foreground">{i.title}</div>
                  <span
                    className={`text-[11px] rounded-full px-2 py-0.5 ${
                      i.grounded ? "bg-success/10 text-success" : "bg-accent text-accent-foreground"
                    }`}
                  >
                    {i.tag} · {i.evalScore.toFixed(2)}
                  </span>
                </div>
                <div className="text-sm text-muted-foreground mt-1">{i.summary}</div>
                <div className="mt-3 flex items-center gap-2 text-[11px] text-muted-foreground">
                  <Sparkles className="h-3 w-3" /> Fireworks AI · {i.id}
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
